FROM maven:3-openjdk-17 AS builder
WORKDIR /app
COPY . .
RUN ["mvn", "package", "-Dmaven.test.skip=true"]


FROM openjdk:17-oracle
WORKDIR /app
COPY --from=builder /app/target/smackBE-0.0.1-SNAPSHOT.jar smackBE.jar

ENV SPRING_DATASOURCE_URL="CHANGETHIS"
ENV SPRING_DATASOURCE_USERNAME="CHANGETHIS"
ENV SPRING_DATASOURCE_PASSWORD="CHANGETHIS"

ENV SPRING_DATA_MONGODB_URI="CHANGETHIS"
ENV SPRING_DATA_MONGODB_DATABASE="smackMessages"

ENV SPRING_RABBITMQ_HOST="localhost"
ENV SPRING_RABBITMQ_PORT=5672
ENV SPRING_RABBITMQ_USERNAME="guest"
ENV SPRING_RABBITMQ_PASSWORD="guest"

ENV SPOTIFY_CLIENT_ID=""
ENV SPOTIFY_CLIENT_SECRET=""

ENV JWT_AUTH_SECRET="SUCHSECRETMUCHHUSH"
ENV JWT_AUTH_VALIDITY=43200000

ENV SERVER_PORT=8080

EXPOSE ${SERVER_PORT}

ENTRYPOINT ["java", "-jar", "/app/smackBE.jar"]
