logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true

jwt:
  auth:
    secret: changethis
    validity: 12345

spotify:
  client:
    id: changethis
    secret: changethis